language: go
go:
  - 1.4
  - 1.5
  - tip
addons:
  apt:
    packages:
      - libmagic-dev
before_install:
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls
after_script:
  - sh `pwd`/scripts/coverage --coveralls
